### ISSUE TITLE
Prevent switching to super admin?

### ISSUE THREAD

**Issue by lkraav** [johnbillion/user-switching-for-regular-admins#1]
Hi. I don't see any docs and It's hard to tell directly from the code whether subsite admins would be prevented from "switching up". Which is the case?

**Comment by johnbillion** [comment]
You're right, it's not clear. I'll add some docs.

The `!is_super_admin( $args[2] )` condition [here](https://github.com/johnbillion/user-switching-for-regular-admins/blob/master/usfra.php#L29) prevents admins from switching up to super admin accounts.

**Comment by lkraav** [comment]
Sweet. So this is safe to deploy as is. Thanks!
